### PR TITLE
Return alist key as a symbol

### PR DESCRIPTION
**Pull request by conao3**
Return alist key as a symbol.
This idea from #13.

### before
```elisp
(let ((yaml "
uri: https://www.google.co.jp
user: foo
password: password
"))
  (yaml-parse-string yaml :object-type 'alist))
;;=> (("uri" . "https://www.google.co.jp") ("user" . "foo") ("password" . "password"))
```
### after
```elisp
(let ((yaml "
uri: https://www.google.co.jp
user: foo
password: password
"))
  (yaml-parse-string yaml :object-type 'alist))
;;=> ((uri . "https://www.google.co.jp") (user . "foo") (password . "password"))
```

### CODE REVIEW

**Comment by zkry** [comment]
Thanks for contributing! There are a few things I see should be done in this PR:

- The default key type for maps should a string as this is what `json-parse-string` defaults to. I think the logic for this would look like what you did for the plist/keyword change. Feel free to refactor those case statements if you think they're starting to look too messy.
- Changing the default key type for alists to symbols seems to have broken the tests. To fix them you can either change the tests to expect keywords or add the key-type parameter as a string.

**Comment by conao3** [comment]
> The default key type for maps should a string

So, I will take down this PR? (Of course, this is fine.)

**Comment by zkry** [comment]
I don't think it needs to be closed since we still want to make symbols the default for alists.

**Comment by conao3** [comment]
OK, I'll fix this branch after.

**Comment by conao3** [comment]
Sorry, I'm busy recently, I cannot take time on this issue. I fix this branch. Please try it.

(If the object key has space or newline, there is `intern` hack to extract the value. But this is rere case I think. How about think?)

**Comment by zkry** [comment]
No problem, the changes look good! It makes sense that you'd have to use `inter` for the keys with whitespace.

**Pull request merged**
